### Rota para pegar os equipamentos
GET http://localhost:3000/equipamentos

### fechando a requicisao

### Rota criando o equipamento
POST http://localhost:3000/equipamentos
Content-Type: application/json

{
    
    "nomeFuncionario": "José",
    "nomeEquipamento":"Capacete",
    "dataRetirada":"03-03-2024",
    "dataDevolucao":"10-03-2025",
    "status":"em perfeito estado"
    
}

### 


###pegar Equipamento pelo id
GET http://localhost:3000/equipamentos/5
Content-Type: application/json

###

### PUT-editar equipamento

PUT http://localhost:3000/equipamento/2
Content-Type: application/json

{
  "id":"2",
  "novoFuncionario": "Cesar",
  "novoEquipamento": "Capacete",
  "novaDataRetirada": "15-02-2025",
  "novaDataDevolucao": "22-03-2025",
  "novoStatus": "perfeito estado"

}

###

### DELETE- excluir um equipamento
DELETE http://localhost:3000/equipamentos/5
Content-Type: application/json

###

###

### DELETE-excluir todos os produtos
DELETE http://localhost:3000/equipamentos
Content-Type: application